# Generated by Django 4.0.5 on 2022-06-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link above to read post', max_length=200),
        ),
    ]
