# Generated by Django 4.0.5 on 2022-06-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0013_profile_instagram_url_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='wevbsite_url',
            new_name='website_url',
        ),
    ]
