# Generated by Django 4.0.5 on 2022-06-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
